name: build

on:
  pull_request:
    branches: [ master ]

jobs:
  emscripten:
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            cmake \
            ninja-build \
            pkg-config

      - name: Install Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

          echo "EMSDK=${{ github.workspace }}/emsdk" >> $GITHUB_ENV
          echo "EM_CONFIG=${{ github.workspace }}/emsdk/.emscripten" >> $GITHUB_ENV
          echo "${{ github.workspace }}/emsdk" >> $GITHUB_PATH

      - name: Configure (Web)
        run: |
          source emsdk/emsdk_env.sh

          emcmake cmake \
            --preset=web-release \
            -DBUILD_SERVER=OFF \
            -DBUILD_RUNTIME=OFF \
            -DBUILD_TESTING=ON

      - name: Build
        run: |
          source emsdk/emsdk_env.sh

          emmake cmake --build build/webgl/release --parallel $(nproc)